// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5SP7JT_dxUXX6Yx7RHAhoMxC2F5V6uY',
    appId: '1:924607037443:web:b96324f0ffd4bc10128e36',
    messagingSenderId: '924607037443',
    projectId: 'flutter-chat-app-c03af',
    authDomain: 'flutter-chat-app-c03af.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c03af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9lydtj1ILvEUutLTlOdCoyzZ0loq84E',
    appId: '1:924607037443:android:23f43130a1db23c1128e36',
    messagingSenderId: '924607037443',
    projectId: 'flutter-chat-app-c03af',
    storageBucket: 'flutter-chat-app-c03af.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV5SP7JT_dxUXX6Yx7RHAhoMxC2F5V6uY',
    appId: '1:924607037443:web:aaf86dea7991fea6128e36',
    messagingSenderId: '924607037443',
    projectId: 'flutter-chat-app-c03af',
    authDomain: 'flutter-chat-app-c03af.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c03af.appspot.com',
  );

}